### ISSUE TITLE
using indicators for turbo strategy

### ISSUE THREAD

**Issue by ghost** [askmike/whaleclub#3]
Hi, I would like to use a stochastic and moving average for opening positions on turbo every 5 min intervals. What would be the best way to do this? I can already open turbo positions

**Comment by askmike** [comment]
This is just a library that connects to whaleclub. If you want that kind of logic you are probably going to need a TA library like [talib](http://npmjs.com/package/talib) or [tulip indicators](https://www.npmjs.com/package/tulind) (they can calculate moving averages and stochastic for you).
